name = "rawr-ed2"
compatibility_date = "2024-11-01"
pages_build_output_dir = "public"

[vars]
BRAND_NAME = "RISE"
TYPE_MIN_WPM_ELIMINATION = "65"
WEB_TYPING_RESULTS_CATEGORY_ID = "1494741227772448788"
WEB_TYPING_RESULTS_PRIVATE_ROLE_ID = "1494741347691925635"
